name: Release

on:
  push:
    branches: [main]
    paths:
      - "packages/**"
      - ".changeset/**"
      - "pnpm-lock.yaml"
  workflow_dispatch: {}

concurrency:
  group: release
  cancel-in-progress: false

permissions:
  contents: write
  id-token: write
  pull-requests: write

env:
  CI: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.4.0
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: "https://registry.npmjs.org"

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build:packages

      # 收集构建产物并压缩
      - name: 准备发布资产
        run: |
          mkdir -p release-assets
          for pkg in packages/*; do
            if [ -d "$pkg/dist" ]; then
              pkg_name=$(basename "$pkg")
              zip -r "release-assets/$pkg_name-dist.zip" "$pkg/dist"
              tar -czf "release-assets/$pkg_name-dist.tar.gz" -C "$pkg" dist
            fi
          done
          echo "准备发布的资产:"
          ls -la release-assets/

      # 版本更新 + 发布到 npm（可选）
      - name: 版本更新 & 发布
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: version packages"
          title: "chore: version packages"
          version: pnpm ci:version
          publish: pnpm ci:publish   # 这里会真正执行 npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 创建 GitHub Release 并上传资产
      - name: 创建 GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.changesets.outputs.tag || github.ref_name }}
          body_path: CHANGELOG.md
          files: |
            release-assets/*.zip
            release-assets/*.tar.gz
          draft: false
          prerelease: false
